#!/usr/bin/with-contenv bash

# Copy deployed.txt file to /config
[[ ! -f /config/deployed-koko.txt ]] && \
    cp /app/koko/deployed-koko.txt /config/deployed-koko.txt

# Create dummy cli_config
[[ ! -f /config/cli_config ]] && \
    echo {} > /config/cli_config

# Create ask config folder if doesn't exist
[[ ! -d /root/.ask ]] && \
    mkdir /root/.ask

# Create symlink of cli_config if doesn't exist
[[ ! -L /root/.ask/cli_config ]] && \
	ln -s /config/cli_config /root/.ask/cli_config

# create kodi.config if doesn't exist
[[ ! -f /config/kodi.config ]] && \
	cd /config && \
	lexigram init-config \

# remove /app/koko/kodi.config if exists
[[ -f /app/koko/kodi.config ]] && \
	rm /app/koko/kodi.config

# Create symlink of kodi.config if doesn't exist
[[ ! -L /app/koko/kodi.config ]] && \
    ln -s /config/kodi.config /app/koko/kodi.config

#Necessary variables
KOKO_VERSION=$(cat /app/koko/version.txt)
DEPLOYED_VERSION=$(cat /config/deployed-koko.txt)

# Check for credentials in cli_config
grep -q token /config/cli_config
if [ $? != 0 ]
 then
  echo "Please see the readme at https://github.com/linuxserver/docker-koko#application-setup to register your Amazon Developer Account and configure your kodi.config file."
 else 
  echo "Amazon Developer Account already linked"
   if [ "${KOKO_VERSION}" = "${DEPLOYED_VERSION}" ]; then
     echo "${KOKO_VERSION} in this container is the same as the version previously deployed, not redeploying"
    else
     echo "Either never deployed previously or previous deployed version of Koko ${DEPLOYED_VERSION} is different to version ${KOKO_VERSION} in this container, so deploying" && \
     cd /app/koko && \
     if [ ! -d /app/koko/koko ]; then
       lexigram init-skill koko
     fi
     lexigram deploy koko --source-dir /app/koko --invocation-name ${INVOCATION_NAME} --url ${URL_ENDPOINT} && \
     echo "${KOKO_VERSION}" > /config/deployed.txt && \
     echo "    Koko ${KOKO_VERSION} successfully deployed with invocation name ${INVOCATION_NAME} at ${URL_ENDPOINT}"
   fi
fi

# permissions
chown -R abc:abc \
	/app \
	/config
